<?php

namespace YS\DiscussBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiscussRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscussRepository extends EntityRepository
{

}